services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped

    runtime: nvidia

    environment:
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
      OLLAMA_VULKAN: "false"

    ports:
      - "11434:11434"

    volumes:
      - ollama:/root/.ollama
      - /home/mbeldis/Work/ft_ollama/03_TrainMath/gguf:/models:ro

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: unless-stopped

    depends_on:
      - ollama

    ports:
      - "3000:8080"

    environment:
      OLLAMA_BASE_URL: http://ollama:11434

    volumes:
      - open-webui:/app/backend/data

volumes:
  ollama:
  open-webui:


